name: test
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  test:
    name: Test ${{ matrix.package-manager }} on macos-latest
    strategy:
      matrix:
        include:
          - package-manager: "npm"
            node-version: "18"
          - package-manager: "yarn"
            node-version: "18"
          - package-manager: "yarn-berry"
            node-version: "18"
          - package-manager: "pnpm"
            node-version: "18"
          - package-manager: "deno"
            node-version: "18"
          - package-manager: "vite-plus"
            node-version: "24"
    # zsh is pre-installed on macos-latest
    # https://github.com/actions/runner-images/issues/264
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno
        if: matrix.package-manager == 'deno'
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.x'
      - name: Enable corepack
        # https://github.com/nodejs/corepack/issues/612
        if: matrix.package-manager != 'deno'
        run: npm install -g corepack && corepack enable
      - name: Setup Vite+
        if: matrix.package-manager == 'vite-plus'
        env:
          VP_VERSION: "0.2.2"
        run: |
          curl -fsSL https://vite.plus | bash
          echo "$HOME/.vite-plus/bin" >> "$GITHUB_PATH"
      - name: Check Vite+ version
        if: matrix.package-manager == 'vite-plus'
        run: vp --version
      - name: Test
        shell: zsh {0}
        run: |
          set -e
          # enable compinit before loading
          autoload -Uz compinit && compinit
          # load ni.zsh
          source ./ni.zsh
          # move to test dir
          cd test/${{ matrix.package-manager }}
          
          # Install dependencies
          if [ "${{ matrix.package-manager }}" = "deno" ]; then
            # Add dependencies first
            ni add jsr:@std/path@0.220.1
            ni add chalk@5.3.0
            # Run tests and scripts
            ni test
            ni run main
            # Remove packages
            ni remove chalk
            ni remove jsr:@std/path
          else
            ni
            ni test
            ni run main
            ni exec envinfo
            ni add lodash
            ni remove lodash
          fi
